
name: Dart

language: dart

dart:
  - stable

cache:
  directories:
    - $HOME/.pub-cache

script:
  - flutter pub get
  - flutter build apk --release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/app/outputs/flutter-apk/app-release.apk
  skip_cleanup: true